import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./hooks/useAuth";
import ComingSoon from "@/components/ComingSoon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Urbanary",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased`}
      >
        <ComingSoon />
        <AuthProvider
          allowUnauthenticatedPaths={[
            "/login",
            "/signup",
            "/forgot-password",
            "/verify-email",
            "/reset-password",
            "/resend-verification-email",
          ]}
        >
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
